[
    {
        "customFields": null,
        "type": "Professional Services",
        "tasks": [
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Project Creation",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Project Templates",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Cross Project Gantt View",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Filters and View Settings",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Project Details",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Managing List Views",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Project Gantt, Board, and List Views",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Project Task Details",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Sub Tasks",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-02",
                "parentIndex": null,
                "name": "Review How-To",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Set Milestones App visibility by profile",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-10-03",
                "parentIndex": 0,
                "name": "Assigning Milestones App",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Add additional Standard and Custom tabs",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Set default landing tab",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-10-03",
                "parentIndex": 0,
                "name": "Configuring Milestones App",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Identify standard projects",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "List Tasks and Task Duration",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "List Sub Tasks",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Build Project Structure",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Activate Project Template",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-10-03",
                "parentIndex": 0,
                "name": "Set Up Project Templates",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Project Template list view",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "My Projects list view",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Additional Views",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-10-03",
                "parentIndex": 0,
                "name": "Create Standard List Views",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Create Lookup Relationships to Standard & Custom Objects",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Create Custom Fields",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Modify Milestones field sets",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-10-03",
                "parentIndex": 2,
                "name": "Advanced Configuration (Optional)",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Automate Project Creation",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Additional workflows",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-10-03",
                "parentIndex": 2,
                "name": "Advanced Workflows (Optional)",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Build custom Milestones reports",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Build custom Milestones dashboards",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-10-03",
                "parentIndex": 4,
                "name": "Advanced Reports (Optional)",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Demo Cloud Coach Milestones",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Manual Project Creation",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Creating Projects from Template",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Managing Projects",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Completing Project Work",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Q & A",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-10-03",
                "parentIndex": 4,
                "name": "User Training",
                "isAssigned": true,
                "duration": 1,
                "description": null
            }
        ],
        "start": "2017-01-02",
        "name": "Template | Cloud Coach Implementation",
        "description": "Implementation project plan for Cloud Coach project management",
		"template": true
    },
    {
        "customFields": null,
        "type": "Marketing",
        "tasks": [
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Workshop",
                        "complete": true
                    }
                ],
                "status": "Completed",
                "start": "2017-01-16",
                "parentIndex": null,
                "name": "Marketing Plan",
                "isAssigned": true,
                "duration": 3,
                "description": null,
                "completedDate": "2017-01-24"
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Booth signage",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Design handouts",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "E-mail campaign design",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-12",
                "parentIndex": 0,
                "name": "Graphic Design",
                "isAssigned": true,
                "duration": 7,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Outbound marketing",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Partner webinars",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-12",
                "parentIndex": 0,
                "name": "Partner Outreach",
                "isAssigned": true,
                "duration": 10,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Outbound marketing",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Execute social media strategy",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-12",
                "parentIndex": 0,
                "name": "Customer Outreach",
                "isAssigned": true,
                "duration": 10,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Layout",
                        "complete": false
                    }
                ],
                "status": "On Hold",
                "start": "2016-12-14",
                "parentIndex": 0,
                "name": "Booth Design",
                "isAssigned": true,
                "duration": 7,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Generate ideas",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Evaluate ideas",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Reach out to sponsors",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-16",
                "parentIndex": 0,
                "name": "Drawing / Give-Away",
                "isAssigned": true,
                "duration": 6,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Plan",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Shoot",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Edit",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-17",
                "parentIndex": 5,
                "name": "Plan, Shoot, Edit Video",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Signage",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Materials",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "A/V",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-11",
                "parentIndex": 5,
                "name": "Setup Booth",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [],
                "status": "Not Started",
                "start": "2016-12-12",
                "parentIndex": 7,
                "name": "Schedule One-on-One Demos",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [],
                "status": "Not Started",
                "start": "2016-12-12",
                "parentIndex": 7,
                "name": "Photography",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Scrub data",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Segment users",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Import to Salesforce",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Create Surveys",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Send Surveys",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-12",
                "parentIndex": 9,
                "name": "Send Surveys",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Lessons learned",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "KPIs",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-12",
                "parentIndex": 9,
                "name": "Takeaways meeting",
                "isAssigned": true,
                "duration": 1,
                "description": null
            }
        ],
        "start": "2017-01-16",
        "name": "Dreamforce Booth Plan",
        "description": "Booth plan for Dreamforce event"
    },
    {
        "customFields": null,
        "type": "Marketing",
        "tasks": [
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Workshop",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2017-01-02",
                "parentIndex": null,
                "name": "Marketing Plan",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Booth signage",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Design handouts",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "E-mail campaign design",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-10-18",
                "parentIndex": 0,
                "name": "Graphic Design",
                "isAssigned": true,
                "duration": 7,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Outbound marketing",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Partner webinars",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-10-18",
                "parentIndex": 0,
                "name": "Partner Outreach",
                "isAssigned": true,
                "duration": 10,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Outbound marketing",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Execute social media strategy",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-10-18",
                "parentIndex": 0,
                "name": "Customer Outreach",
                "isAssigned": true,
                "duration": 10,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Layout",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-10-20",
                "parentIndex": 0,
                "name": "Booth Design",
                "isAssigned": true,
                "duration": 7,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Generate ideas",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Evaluate ideas",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Reach out to sponsors",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-10-24",
                "parentIndex": 0,
                "name": "Drawing / Give-Away",
                "isAssigned": true,
                "duration": 6,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Plan",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Shoot",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Edit",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-10-28",
                "parentIndex": 0,
                "name": "Plan, Shoot, Edit Video",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Signage",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Materials",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "A/V",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-11-17",
                "parentIndex": 0,
                "name": "Setup Booth",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Schedule Demos",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-10-18",
                "parentIndex": 7,
                "name": "Schedule One-on-One Demos",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Event photography",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-10-18",
                "parentIndex": 7,
                "name": "Photography",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Scrub data",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Segment users",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Import to Salesforce",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Create Surveys",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Send Surveys",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-10-18",
                "parentIndex": 9,
                "name": "Send Surveys",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Lessons learned",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "KPIs",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-10-18",
                "parentIndex": 9,
                "name": "Takeaways meeting",
                "isAssigned": true,
                "duration": 1,
                "description": null
            }
        ],
        "start": "2017-01-02",
        "name": "Template | Trade Show",
        "description": "Trade show project plan",
		"template": true
    },
    {
        "customFields": null,
        "type": "Professional Services",
        "tasks": [
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Kickoff Call",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Workshop",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Prioritize Requirements",
                        "complete": true
                    }
                ],
                "status": "Completed",
                "start": "2017-01-02",
                "parentIndex": null,
                "name": "Requirements Gathering",
                "isAssigned": true,
                "duration": 3,
                "description": null,
                "completedDate": "2017-01-05"
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Solution Design",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Data Migration Requirements",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Map Processes",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2017-01-02",
                "parentIndex": 0,
                "name": "Solution Design & Project Plan",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Profiles",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Sharing Rules",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Role Hierarchy",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Permissions",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2017-01-02",
                "parentIndex": 1,
                "name": "Setup Security Model",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Layout, Fields & Record Types: Account",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Layout, Fields & Record Types: Contacts",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Layout, Fields & Record Types: Leads",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Layout, Fields & Record Types: Opportunities",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2017-01-02",
                "parentIndex": 2,
                "name": "Standard Object Configuration",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Alert & Notifications",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Validation Rules",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Approval Processes",
                        "complete": false
                    }
                ],
                "status": "On Hold",
                "start": "2017-01-02",
                "parentIndex": 3,
                "name": "Workflow Rules",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Outlook Integration",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "HR system integration",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Finance system integration",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-02",
                "parentIndex": 4,
                "name": "Integrations",
                "isAssigned": true,
                "duration": 5,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Configuration Review (Internal)",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Update Configuration",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "UAT",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-02",
                "parentIndex": 5,
                "name": "User Acceptance Testing",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Prep data",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Migrate Data",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Audit Data",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-02",
                "parentIndex": 6,
                "name": "Data Migration",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Training Materials",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Config. Documentation",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Admin Training",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "End User Training",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-02",
                "parentIndex": 7,
                "name": "User Training",
                "isAssigned": true,
                "duration": 3,
                "description": null
            }
        ],
        "start": "2017-01-02",
        "name": "TechBuild Sales Cloud Implementation",
        "description": "Implementation of Sales Cloud for TechBuild Co."
    },
    {
        "customFields": null,
        "type": "Professional Services",
        "tasks": [
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Kickoff Call",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Workshop",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Prioritize Requirements",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-02",
                "parentIndex": null,
                "name": "Requirements Gathering",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Map Processes",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Solution Design",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Data Migration Requirements",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-09-01",
                "parentIndex": 0,
                "name": "Solution Design & Project Plan",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Profiles",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Sharing Rules",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Role Hierarchy",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Permissions",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-09-01",
                "parentIndex": 1,
                "name": "Setup Security Model",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Layout, Fields & Record Types: Account",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Layout, Fields & Record Types: Contacts",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Layout, Fields & Record Types: Leads",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Layout, Fields & Record Types: Opportunities",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-09-01",
                "parentIndex": 2,
                "name": "Standard Object Configuration",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Alert & Notifications",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Validation Rules",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Approval Processes",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-09-01",
                "parentIndex": 3,
                "name": "Workflow Rules",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Outlook Integration",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "HR system integration",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Finance system integration",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-09-01",
                "parentIndex": 4,
                "name": "Integrations",
                "isAssigned": true,
                "duration": 5,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Configuration Review (Internal)",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Update Configuration",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "UAT",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-09-01",
                "parentIndex": 5,
                "name": "User Acceptance Testing",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Prep data",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Migrate Data",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Audit Data",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-09-01",
                "parentIndex": 6,
                "name": "Data Migration",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Training Materials",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Config. Documentation",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Admin Training",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "End User Training",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-09-01",
                "parentIndex": 7,
                "name": "User Training",
                "isAssigned": true,
                "duration": 3,
                "description": null
            }
        ],
        "start": "2017-01-02",
        "name": "Template | Sales Cloud Implementation",
        "description": "Sales Cloud implementation project plan",
		"template": true
    },
    {
        "customFields": null,
        "type": "Customer Onboarding",
        "tasks": [
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Review Sales Requirements",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Identify Key Stakeholders",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Plan Kick-Off Call",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-02",
                "parentIndex": null,
                "name": "Meeting: Account Team & Project Delivery",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Introductions",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "High level business outcomes",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Deliverables",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Roles & Communication",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Project Schedule",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Risks",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 0,
                "name": "Project Kickoff Meeting",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Deliverables",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Measures of Success",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Risk Management Plan",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Communication Schedule",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Project Schedule",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Resource Assignment",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 1,
                "name": "Create Project Plan",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Basic (text, number, picklists)",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Advanced (Formulas)",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Layouts",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 2,
                "name": "Project Plan Sign Off",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Business Logic",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Design Process",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Build Workflows",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 3,
                "name": "Configure Fields",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Executive Reports & Dashboard",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Management Reports & Dashboard",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Individual Contributor Reports & Dashboard",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 4,
                "name": "Build Reports",
                "isAssigned": true,
                "duration": 5,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Working Days",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Costing",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Color Schemes",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 4,
                "name": "Configure Settings",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Business Logic",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Design Process",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Build Workflows",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 4,
                "name": "Configure Workflows",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Management security",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Individual contributor security",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 4,
                "name": "User Security",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Execute unit test script",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 8,
                "name": "Unit Testing",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Load data in sandbox",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Verify data",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 8,
                "name": "Data Import Validation",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Verify workflow execution",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 8,
                "name": "Workflow Validation",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Standard functionality test",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Custom functionality test",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 9,
                "name": "Functional Testing",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Page layouts",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Visibility settings",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Clickpath",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Workflows",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 10,
                "name": "User Acceptance Testing",
                "isAssigned": true,
                "duration": 5,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Security",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Configuration & Settings",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Workflow Review",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 11,
                "name": "System Admin Training",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Staging",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Deployment",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Validation",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 12,
                "name": "Go-live",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Client support sign-off",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-11-23",
                "parentIndex": 13,
                "name": "Support Handoff",
                "isAssigned": true,
                "duration": 4,
                "description": null
            }
        ],
        "start": "2017-01-02",
        "name": "Template | Customer Onboarding",
        "description": "Customer onboarding project plan",
		"template": true
    },
    {
        "customFields": null,
        "type": "Professional Services",
        "tasks": [
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Project Creation",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Project Templates",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Cross Project Gantt View",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Filters and View Settings",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Project Details",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Managing List Views",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Project Gantt, Board, and List Views",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Project Task Details",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Sub Tasks",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-30",
                "parentIndex": null,
                "name": "Review How-To",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Set Milestones App visibility by profile",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Review permission sets",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-21",
                "parentIndex": 0,
                "name": "Assigning Milestones App",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Add additional Standard and Custom tabs",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Set default landing tab",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-21",
                "parentIndex": 0,
                "name": "Configuring Milestones App",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Identify standard projects",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "List Tasks and Task Duration",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "List Sub Tasks",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Build Project Structure",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Activate Project Template",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-21",
                "parentIndex": 0,
                "name": "Set Up Project Templates",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Project Template list view",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "My Projects list view",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Additional Views",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-21",
                "parentIndex": 0,
                "name": "Create Standard List Views",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Create Lookup Relationships to Standard & Custom Objects",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Create Custom Fields",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Modify Milestones field sets",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-02-10",
                "parentIndex": 2,
                "name": "Advanced Configuration (Optional)",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Automate Project Creation",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Additional workflows",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-02-06",
                "parentIndex": 2,
                "name": "Advanced Workflows (Optional)",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Build custom Milestones reports",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Build custom Milestones dashboards",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-02-10",
                "parentIndex": 4,
                "name": "Advanced Reports (Optional)",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Demo Cloud Coach Milestones",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Manual Project Creation",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Creating Projects from Template",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Managing Projects",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Completing Project Work",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Q & A",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-02-10",
                "parentIndex": 4,
                "name": "User Training",
                "isAssigned": true,
                "duration": 1,
                "description": null
            }
        ],
        "start": "2017-01-30",
        "name": "Cloud Coach Implementation - TechBuild Co",
        "description": "Implementation of Cloud Coach Professional for Techbuild Co."
    },
    {
        "customFields": null,
        "type": "Customer Onboarding",
        "tasks": [
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Review Sales Requirements",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Identify Key Stakeholders",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Plan Kick-Off Call",
                        "complete": true
                    }
                ],
                "status": "Completed",
                "start": "2017-01-24",
                "parentIndex": null,
                "name": "Meeting: Account Team & Project Delivery",
                "isAssigned": true,
                "duration": 1,
                "description": null,
                "completedDate": "2017-01-24"
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Introductions",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Deliverables",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Roles & Communication",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Project Schedule",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Risks",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "High level business outcomes",
                        "complete": true
                    }
                ],
                "status": "Completed",
                "start": "2017-01-26",
                "parentIndex": 0,
                "name": "Project Kickoff Meeting",
                "isAssigned": true,
                "duration": 1,
                "description": null,
                "completedDate": "2017-01-25"
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Deliverables",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Measures of Success",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Risk Management Plan",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Communication Schedule",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Project Schedule",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Resource Assignment",
                        "complete": false
                    }
                ],
                "status": "Completed",
                "start": "2016-12-01",
                "parentIndex": 1,
                "name": "Create Project Plan",
                "isAssigned": true,
                "duration": 2,
                "description": null,
                "completedDate": "2017-01-31"
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Basic (text, number, picklists)",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Advanced (Formulas)",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Layouts",
                        "complete": false
                    }
                ],
                "status": "On Hold",
                "start": "2016-12-01",
                "parentIndex": 2,
                "name": "Project Plan Sign Off",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Business Logic",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Design Process",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Build Workflows",
                        "complete": true
                    }
                ],
                "status": "Completed",
                "start": "2016-12-01",
                "parentIndex": 3,
                "name": "Configure Fields",
                "isAssigned": true,
                "duration": 3,
                "description": null,
                "completedDate": "2017-02-06"
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Executive Reports & Dashboard",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Management Reports & Dashboard",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Individual Contributor Reports & Dashboard",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-12-01",
                "parentIndex": 4,
                "name": "Build Reports",
                "isAssigned": true,
                "duration": 5,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Working Days",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Costing",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Color Schemes",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-12-01",
                "parentIndex": 4,
                "name": "Configure Settings",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Business Logic",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Design Process",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Build Workflows",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-12-01",
                "parentIndex": 4,
                "name": "Configure Workflows",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Individual contributor security",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Management security",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-12-01",
                "parentIndex": 4,
                "name": "User Security",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Execute unit test script",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-01",
                "parentIndex": 8,
                "name": "Unit Testing",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Load data in sandbox",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Verify data",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-01",
                "parentIndex": 8,
                "name": "Data Import Validation",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Verify workflow execution",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-01",
                "parentIndex": 8,
                "name": "Workflow Validation",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Standard functionality test",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Custom functionality test",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-01",
                "parentIndex": 9,
                "name": "Functional Testing",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Page layouts",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Visibility settings",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Clickpath",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Workflows",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-01",
                "parentIndex": 10,
                "name": "User Acceptance Testing",
                "isAssigned": true,
                "duration": 5,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Security",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Configuration & Settings",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Workflow Review",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-01",
                "parentIndex": 11,
                "name": "System Admin Training",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Staging",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Deployment",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Validation",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-01",
                "parentIndex": 12,
                "name": "Go-live",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Client support sign-off",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-01",
                "parentIndex": 13,
                "name": "Support Handoff",
                "isAssigned": true,
                "duration": 4,
                "description": null
            }
        ],
        "start": "2017-01-24",
        "name": "Acme Inc. Onboarding Project",
        "description": "Onboarding of Acme Inc."
    },
    {
        "customFields": null,
        "type": "Customer Onboarding",
        "tasks": [
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Kickoff Call",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Workshop",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Prioritize Requirements",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-02-14",
                "parentIndex": null,
                "name": "Requirements Gathering",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Solution Design",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Data Migration Requirements",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Map Processes",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-02-14",
                "parentIndex": 0,
                "name": "Solution Design & Project Plan",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Profiles",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Sharing Rules",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Role Hierarchy",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Permissions",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-26",
                "parentIndex": 1,
                "name": "Setup Security Model",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Layout, Fields & Record Types: Account",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Layout, Fields & Record Types: Contacts",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Layout, Fields & Record Types: Leads",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Layout, Fields & Record Types: Opportunities",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-26",
                "parentIndex": 2,
                "name": "Standard Object Configuration",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Alert & Notifications",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Validation Rules",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Approval Processes",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-26",
                "parentIndex": 3,
                "name": "Workflow Rules",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Outlook Integration",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "HR system integration",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Finance system integration",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-26",
                "parentIndex": 4,
                "name": "Integrations",
                "isAssigned": true,
                "duration": 5,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Configuration Review (Internal)",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Update Configuration",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "UAT",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-26",
                "parentIndex": 5,
                "name": "User Acceptance Testing",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Prep data",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Migrate Data",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Audit Data",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-26",
                "parentIndex": 6,
                "name": "Data Migration",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Training Materials",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Config. Documentation",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Admin Training",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "End User Training",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-01-26",
                "parentIndex": 7,
                "name": "User Training",
                "isAssigned": true,
                "duration": 3,
                "description": null
            }
        ],
        "start": "2017-02-14",
        "name": "Acme Inc. - Sales Cloud",
        "description": "Sales Cloud Implementation for Acme Inc."
    },
    {
        "customFields": null,
        "type": "Customer Onboarding",
        "tasks": [
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Review Sales Requirements",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Identify Key Stakeholders",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Plan Kick-Off Call",
                        "complete": true
                    }
                ],
                "status": "Completed",
                "start": "2016-12-26",
                "parentIndex": null,
                "name": "Meeting: Account Team & Project Delivery",
                "isAssigned": true,
                "duration": 1,
                "description": null,
                "completedDate": "2016-12-28"
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Introductions",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Deliverables",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Roles & Communication",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Project Schedule",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Risks",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "High level business outcomes",
                        "complete": true
                    }
                ],
                "status": "Completed",
                "start": "2016-12-26",
                "parentIndex": 0,
                "name": "Project Kickoff Meeting",
                "isAssigned": true,
                "duration": 1,
                "description": null,
                "completedDate": "2016-12-30"
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Deliverables",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Measures of Success",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Risk Management Plan",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Communication Schedule",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Project Schedule",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Resource Assignment",
                        "complete": false
                    }
                ],
                "status": "Completed",
                "start": "2016-12-26",
                "parentIndex": 1,
                "name": "Create Project Plan",
                "isAssigned": true,
                "duration": 2,
                "description": null,
                "completedDate": "2017-01-03"
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Basic (text, number, picklists)",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Advanced (Formulas)",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Layouts",
                        "complete": false
                    }
                ],
                "status": "Completed",
                "start": "2016-12-26",
                "parentIndex": 2,
                "name": "Project Plan Sign Off",
                "isAssigned": true,
                "duration": 1,
                "description": null,
                "completedDate": "2017-01-11"
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Business Logic",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Design Process",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Build Workflows",
                        "complete": false
                    }
                ],
                "status": "On Hold",
                "start": "2017-01-16",
                "parentIndex": 3,
                "name": "Configure Fields",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Executive Reports & Dashboard",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Management Reports & Dashboard",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Individual Contributor Reports & Dashboard",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-12-26",
                "parentIndex": 4,
                "name": "Build Reports",
                "isAssigned": true,
                "duration": 5,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Working Days",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Costing",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Color Schemes",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-12-26",
                "parentIndex": 4,
                "name": "Configure Settings",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Business Logic",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Design Process",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Build Workflows",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2016-12-26",
                "parentIndex": 4,
                "name": "Configure Workflows",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Individual contributor security",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Management security",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2017-01-23",
                "parentIndex": 4,
                "name": "User Security",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Execute unit test script",
                        "complete": false
                    }
                ],
                "status": "On Hold",
                "start": "2016-12-26",
                "parentIndex": 8,
                "name": "Unit Testing",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Load data in sandbox",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Verify data",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-26",
                "parentIndex": 8,
                "name": "Data Import Validation",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Verify workflow execution",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-26",
                "parentIndex": 8,
                "name": "Workflow Validation",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Standard functionality test",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Custom functionality test",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-26",
                "parentIndex": 9,
                "name": "Functional Testing",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Page layouts",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Visibility settings",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Clickpath",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Workflows",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-26",
                "parentIndex": 10,
                "name": "User Acceptance Testing",
                "isAssigned": true,
                "duration": 5,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Security",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Configuration & Settings",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Workflow Review",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-26",
                "parentIndex": 11,
                "name": "System Admin Training",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Staging",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Deployment",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Validation",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-26",
                "parentIndex": 12,
                "name": "Go-live",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Client support sign-off",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2016-12-26",
                "parentIndex": 13,
                "name": "Support Handoff",
                "isAssigned": true,
                "duration": 4,
                "description": null
            }
        ],
        "start": "2016-12-26",
        "name": "Universal Containers Onboarding",
        "description": "Onboarding of Universal Containers"
    },
    {
        "customFields": null,
        "type": "Marketing",
        "tasks": [
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Workshop",
                        "complete": true
                    }
                ],
                "status": "Completed",
                "start": "2017-01-24",
                "parentIndex": null,
                "name": "Marketing Plan",
                "isAssigned": true,
                "duration": 3,
                "description": null,
                "completedDate": "2017-01-26"
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Booth signage",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Design handouts",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "E-mail campaign design",
                        "complete": false
                    }
                ],
                "status": "Completed",
                "start": "2017-02-08",
                "parentIndex": 0,
                "name": "Graphic Design",
                "isAssigned": true,
                "duration": 7,
                "description": null,
                "completedDate": "2017-02-24"
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Outbound marketing",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Partner webinars",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2017-02-08",
                "parentIndex": 0,
                "name": "Partner Outreach",
                "isAssigned": true,
                "duration": 10,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Outbound marketing",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Execute social media strategy",
                        "complete": false
                    }
                ],
                "status": "Completed",
                "start": "2017-02-08",
                "parentIndex": 0,
                "name": "Customer Outreach",
                "isAssigned": true,
                "duration": 10,
                "description": null,
                "completedDate": "2017-02-24"
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Layout",
                        "complete": true
                    },
                    {
                        "customFields": null,
                        "name": "Review",
                        "complete": false
                    }
                ],
                "status": "In Progress",
                "start": "2017-02-10",
                "parentIndex": 0,
                "name": "Booth Design",
                "isAssigned": true,
                "duration": 7,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Generate ideas",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Evaluate ideas",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Reach out to sponsors",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-02-14",
                "parentIndex": 0,
                "name": "Drawing / Give-Away",
                "isAssigned": true,
                "duration": 6,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Plan",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Shoot",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Edit",
                        "complete": false
                    }
                ],
                "status": "On Hold",
                "start": "2017-02-20",
                "parentIndex": 0,
                "name": "Plan, Shoot, Edit Video",
                "isAssigned": true,
                "duration": 3,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Signage",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Materials",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "A/V",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-03-10",
                "parentIndex": 0,
                "name": "Setup Booth",
                "isAssigned": true,
                "duration": 1,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Schedule Demos",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-02-08",
                "parentIndex": 7,
                "name": "Schedule One-on-One Demos",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Event photography",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-02-08",
                "parentIndex": 7,
                "name": "Photography",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Scrub data",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Segment users",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Import to Salesforce",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Create Surveys",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "Send Surveys",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-02-08",
                "parentIndex": 9,
                "name": "Send Surveys",
                "isAssigned": true,
                "duration": 2,
                "description": null
            },
            {
                "customFields": null,
                "subTasks": [
                    {
                        "customFields": null,
                        "name": "Lessons learned",
                        "complete": false
                    },
                    {
                        "customFields": null,
                        "name": "KPIs",
                        "complete": false
                    }
                ],
                "status": "Not Started",
                "start": "2017-02-08",
                "parentIndex": 9,
                "name": "Takeaways meeting",
                "isAssigned": true,
                "duration": 1,
                "description": null
            }
        ],
        "start": "2017-01-24",
        "name": "New York Trade Show",
        "description": "Booth plan for New York Trade Show"
    }
]
