<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>EMEA_New_Referral_added</fullName>
        <description>EMEA New Referral added</description>
        <protected>false</protected>
        <recipients>
            <field>Channel_Manager_Email__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>Referral_Email__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <recipient>rfontcuberta@velcro.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Sales_Email_Templates/Referral</template>
    </alerts>
    <alerts>
        <fullName>EMEA_Referral_Campaign_Member_Notify</fullName>
        <description>EMEA Referral Campaign Member Notify</description>
        <protected>false</protected>
        <recipients>
            <field>Email</field>
            <type>email</type>
        </recipients>
        <recipients>
            <recipient>rfontcuberta@velcro.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Sales_Email_Templates/ReferralMember</template>
    </alerts>
    <alerts>
        <fullName>New_Referral1</fullName>
        <description>New Referral</description>
        <protected>false</protected>
        <recipients>
            <field>Channel_Manager_Email__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>Referral_Email__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <recipient>khaddock@velcro.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>sfadmin@velcro.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Sales_Email_Templates/Referral</template>
    </alerts>
    <alerts>
        <fullName>Referral_Campaign_Member_Notify</fullName>
        <description>Referral Campaign Member Notify</description>
        <protected>false</protected>
        <recipients>
            <field>Email</field>
            <type>email</type>
        </recipients>
        <recipients>
            <recipient>sfadmin@velcro.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Sales_Email_Templates/ReferralMember</template>
    </alerts>
    <fieldUpdates>
        <fullName>Channel_Manager_Email_Update</fullName>
        <description>adds email of referral campaign owner to referral campaign</description>
        <field>Channel_Manager_Email__c</field>
        <formula>Campaign.Channel_ManagerEMAIL__c</formula>
        <name>Channel Manager Email Update</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Contract_Interest</fullName>
        <field>Contact_Interest__c</field>
        <formula>Contact.Additional_Notes__c</formula>
        <name>Contract Interest</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Lead_Interest</fullName>
        <field>Interest__c</field>
        <formula>Lead.Additional_Notes__c</formula>
        <name>Lead Interest</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>Referral_Email</fullName>
        <field>Referral_Email__c</field>
        <formula>Campaign.Referral_Contact_Email__c</formula>
        <name>Referral Email</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <rules>
        <fullName>Channel Manager email</fullName>
        <actions>
            <name>Channel_Manager_Email_Update</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>CampaignMember.CreatedDate</field>
            <operation>equals</operation>
            <value>TODAY</value>
        </criteriaItems>
        <description>add email of the owner of referral campaign</description>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>Contact added to Campaign</fullName>
        <actions>
            <name>Contract_Interest</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Lead_Interest</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>CampaignMember.CreatedDate</field>
            <operation>equals</operation>
            <value>TODAY</value>
        </criteriaItems>
        <criteriaItems>
            <field>Campaign.Type</field>
            <operation>equals</operation>
            <value>Referral Program</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>EMEA New Referral Contact</fullName>
        <actions>
            <name>EMEA_New_Referral_added</name>
            <type>Alert</type>
        </actions>
        <actions>
            <name>EMEA_Referral_Campaign_Member_Notify</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Campaign.RecordTypeId</field>
            <operation>equals</operation>
            <value>Referrals</value>
        </criteriaItems>
        <criteriaItems>
            <field>Lead.Owner_Region__c</field>
            <operation>equals</operation>
            <value>EMEA</value>
        </criteriaItems>
        <criteriaItems>
            <field>Campaign.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </criteriaItems>
        <criteriaItems>
            <field>Campaign.Referral_Contact_Email__c</field>
            <operation>equals</operation>
            <value>rogerfontcuberta@outlook.com</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>New Referral Contact</fullName>
        <actions>
            <name>New_Referral1</name>
            <type>Alert</type>
        </actions>
        <actions>
            <name>Referral_Campaign_Member_Notify</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Campaign.RecordTypeId</field>
            <operation>equals</operation>
            <value>Referrals</value>
        </criteriaItems>
        <criteriaItems>
            <field>Lead.Owner_Region__c</field>
            <operation>notEqual</operation>
            <value>EMEA</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>Referralls</fullName>
        <actions>
            <name>Referral_Email</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <formula>Campaign.RecordType.DeveloperName  = &quot;Referrals&quot;</formula>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
</Workflow>
