 p.c92 {margin-top:6.0pt;margin-right:4.8pt;margin-bottom: 0cm;margin-left:-4.0cm;margin-bottom:.0001pt}
  span.c91 {font-size: 8.5pt;line-height:115%;font-family:Arial Unicode MS;color:black;mso-font-kerning: 0pt;mso-ansi-language:ES;mso-fareast-language:ES}
  table.c90 {margin-left:10pt;border-collapse:collapse;mso-table-layout-alt: fixed;border:none;mso-border-top-alt:solid #CC0033 .5pt;mso-yfti-tbllook:1184; mso-padding-alt:0cm 5.4pt 0cm 5.4pt;mso-border-insideh:none;mso-border-insidev: none}
  tr.c89 {mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:yes; height:1.0cm}
  td.c88 {width:276.7pt;border:none;border-top:solid #CC0033 1.0pt; mso-border-top-alt:solid #CC0033 .5pt;padding:0cm 5.4pt 0cm 5.4pt;height: 1.0cm}
  span.c87 {font-size:6.0pt;font-family:Arial Unicode MS;color:black; mso-font-kerning:0pt;mso-fareast-language:ES}
  span.c86 {font-size:6.0pt;font-family:Arial Unicode MS;color:#CD0033; mso-font-kerning:0pt;mso-fareast-language:ES}
  td.c85 {width:256.6pt;border:none;border-top:solid #CC0033 1.0pt; mso-border-top-alt:solid #CC0033 .5pt;padding:0cm 5.4pt 0cm 5.4pt;height: 1.0cm}
  span.c84 {font-size:6.0pt;font-family:Arial Unicode MS; color:black;}
  p.c83 {margin-bottom:0cm;margin-bottom:.0001pt;line-height: normal;mso-pagination:widow-orphan;mso-layout-grid-align:none;text-autospace: none}
  span.c82 {font-size:6.0pt;font-family:Arial Unicode MS; color:#CD0033;}
  tr.c81 {mso-yfti-irow:3;mso-yfti-lastrow:yes;height:18.25pt;mso-height-rule: exactly}
  td.c80 {width:163.0pt;border-top:none;border-left:solid windowtext 1.0pt; border-bottom:solid windowtext 1.0pt;border-right:none;mso-border-left-alt: solid windowtext .5pt;mso-border-bottom-alt:solid windowtext .5pt;padding: 0cm 5.4pt 0cm 5.4pt;height:18.25pt;mso-height-rule:exactly}
  td.c79 {width:163.95pt;border-top:none;border-left:solid windowtext 1.0pt; border-bottom:solid windowtext 1.0pt;border-right:none;mso-border-left-alt: solid windowtext .5pt;mso-border-bottom-alt:solid windowtext .5pt;padding: 0cm 5.4pt 0cm 5.4pt;height:18.25pt;mso-height-rule:exactly}
  span.c78 {font-family: Arial Unicode MS; font-size: 7.0pt; font-weight: bold; mso-ansi-language: ES; mso-bidi-font-weight: normal}
  td.c77 {width:77.05pt;border:none;border-bottom:solid windowtext 1.0pt; mso-border-left-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt; mso-border-bottom-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt; height:18.25pt;mso-height-rule:exactly}
  td.c76 {width:57.0pt;border-top:none;border-left:none;border-bottom: solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;mso-border-left-alt: solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;mso-border-bottom-alt: solid windowtext .5pt;mso-border-right-alt:solid windowtext .5pt;padding: 0cm 5.4pt 0cm 5.4pt;height:18.25pt;mso-height-rule:exactly}
  td.c75 {width:65.2pt;border-top:none;border-left:none;border-bottom: solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;mso-border-bottom-alt: solid windowtext .5pt;mso-border-right-alt:solid windowtext .5pt;padding: 0cm 5.4pt 0cm 5.4pt;height:18.25pt;mso-height-rule:exactly}
  span.c74 {font-size:7.0pt;font-family:Arial Unicode MS;mso-ansi-language: ES}
  tr.c73 {mso-yfti-irow:2;height:18.25pt;mso-height-rule:exactly}
  p.c72 {font-weight: bold; line-height: normal; margin-bottom: 0cm; margin-left: 0cm; margin-right: -48.1pt; margin-top: 0cm; mso-add-space: auto; mso-bidi-font-weight: normal; mso-pagination: widow-orphan}
  td.c71 {width:163.95pt;background:#CC0033;padding:0cm 5.4pt 0cm 5.4pt; height:18.25pt;mso-height-rule:exactly}
  td.c70 {width:77.05pt;background:#CC0033;padding:0cm 5.4pt 0cm 5.4pt; height:18.25pt;mso-height-rule:exactly}
  p.c69 {font-weight: bold; line-height: normal; margin-bottom: 0cm; margin-left: 0cm; margin-right: -2.25pt; margin-top: 0cm; mso-add-space: auto; mso-bidi-font-weight: normal; mso-pagination: widow-orphan}
  span.c68 {font-size:7.0pt;font-family:Arial Unicode MS; color:white;mso-themecolor:background1}
  td.c67 {width:57.0pt;background:#CC0033;padding:0cm 5.4pt 0cm 5.4pt; height:18.25pt;mso-height-rule:exactly}
  td.c66 {width:65.2pt;background:#CC0033;padding:0cm 5.4pt 0cm 5.4pt; height:18.25pt;mso-height-rule:exactly}
  td.c65 {width:163.0pt;border:none;mso-border-left-alt:solid windowtext .5pt; padding:0cm 5.4pt 0cm 5.4pt;height:18.25pt;mso-height-rule:exactly}
  span.c64 {font-family: Arial Unicode MS; font-size: 7.0pt; font-weight: bold; mso-bidi-font-weight: normal}
  td.c63 {width:241.0pt;border:none;border-right:solid windowtext 1.0pt; mso-border-left-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt; mso-border-right-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt; height:18.25pt;mso-height-rule:exactly}
  span.c62 {font-family: Arial Unicode MS; font-size: 7.0pt; font-weight: bold; line-height: 115%; mso-bidi-font-weight: normal}
  td.c61 {width:122.2pt;border:none;border-right:solid windowtext 1.0pt; mso-border-right-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt; height:18.25pt;mso-height-rule:exactly}
  span.c60 {font-size:7.0pt;font-family:Arial Unicode MS;}
  tr.c59 {mso-yfti-irow:0;mso-yfti-firstrow:yes;height:18.25pt;mso-height-rule: exactly}
  td.c58 {width:163.0pt;background:#CC0033;padding:0cm 5.4pt 0cm 5.4pt; height:18.25pt;mso-height-rule:exactly}
  p.c57 {font-weight: bold; line-height: normal; margin-bottom: 0cm; mso-bidi-font-weight: normal; mso-pagination: widow-orphan}
  td.c56 {width:241.0pt;background:#CC0033;padding:0cm 5.4pt 0cm 5.4pt; height:18.25pt;mso-height-rule:exactly}
  p.c55 {font-weight: bold; margin-bottom: 0cm; margin-left: 0cm; margin-right: 11.4pt; margin-top: 0cm; mso-bidi-font-weight: normal}
  span.c54 {font-size:7.0pt;line-height:115%;font-family:Arial Unicode MS; color:white;mso-themecolor:background1}
  td.c53 {width:122.2pt;background:#CC0033;padding:0cm 5.4pt 0cm 5.4pt; height:18.25pt;mso-height-rule:exactly}
  p.c52 {font-weight: bold; line-height: normal; margin-bottom: 0cm; margin-left: 0cm; margin-right: -2.25pt; margin-top: 0cm; mso-add-space: auto; mso-bidi-font-weight: normal}
  span.c51 {font-size:7.0pt;font-family:Arial Unicode MS;color:white;mso-themecolor: background1}
  p.c50 {margin-top:6.0pt;margin-right:4.8pt;margin-bottom: 0cm;margin-left:0cm;margin-bottom:.0001pt}
  span.c49 {font-size:5.0pt; line-height:115%;font-family:Arial Unicode MS;color:#58595B;mso-font-kerning: 0pt;mso-fareast-language:ES}
  table.c48 {margin-left:10pt;border-collapse:collapse;mso-table-layout-alt: fixed;border:none;mso-border-alt:solid windowtext .5pt;mso-yfti-tbllook:1184; mso-padding-alt:0cm 5.4pt 0cm 5.4pt}
  tr.c47 {mso-yfti-irow:3;mso-yfti-lastrow:yes;min-height:14.0pt}
  td.c46 {width:446.55pt;border:none;border-bottom:solid #7F7F7F 1.0pt; mso-border-bottom-themecolor:text1;mso-border-bottom-themetint:128; mso-border-top-alt:solid #58595B .5pt;mso-border-left-alt:solid #58595B .5pt; padding:0cm 5.4pt 0cm 5.4pt;height:34.0pt}
  td.c45 {width:86.5pt;border-top:none;border-left:solid white 1.0pt; mso-border-left-themecolor:background1;border-bottom:solid #7F7F7F 1.0pt; mso-border-bottom-themecolor:text1;mso-border-bottom-themetint:128; border-right:solid #58595B 1.0pt;mso-border-top-alt:solid #58595B .5pt; mso-border-top-alt:#58595B .5pt;mso-border-left-alt:white .5pt;mso-border-left-themecolor: background1;mso-border-bottom-alt:#7F7F7F 1.0pt;mso-border-bottom-themecolor: text1;mso-border-bottom-themetint:128;mso-border-right-alt:#58595B .5pt; mso-border-style-alt:solid;padding:0cm 5.4pt 0cm 5.4pt;min-height:14.0pt}
  tr.c44 {mso-yfti-irow:2;min-height:14.0pt}
  td.c43 {width:446.55pt;border:none;border-bottom:solid #58595B 1.0pt; mso-border-top-alt:solid #58595B .5pt;mso-border-left-alt:solid #58595B .5pt; mso-border-top-alt:solid #58595B .5pt;mso-border-left-alt:solid #58595B .5pt; mso-border-bottom-alt:solid #58595B .5pt;padding:0cm 5.4pt 0cm 5.4pt; min-height:14.0pt}
  p.c42 {margin-top:0cm;margin-right:1.65pt;margin-bottom: 0cm;margin-left:0cm;margin-bottom:.0001pt;text-align:justify;text-justify: inter-ideograph;mso-hyphenate:none;tab-stops:-36.0pt 0cm 16.8pt 36.0pt 72.0pt 108.0pt 144.0pt 180.0pt 216.0pt 252.0pt 288.0pt 324.0pt 375.05pt 396.0pt 432.0pt 468.0pt 504.0pt 540.0pt 576.0pt}
  td.c41 {width:86.5pt;border-top:none;border-left:solid white 1.0pt; mso-border-left-themecolor:background1;border-bottom:solid #58595B 1.0pt; border-right:solid #58595B 1.0pt;mso-border-top-alt:solid #58595B .5pt; mso-border-alt:solid #58595B .5pt;mso-border-left-alt:solid white .5pt; mso-border-left-themecolor:background1;padding:0cm 5.4pt 0cm 5.4pt; min-height:14.0pt}
  span.c40 {font-size:8.0pt; line-height:115%;font-family:Arial Unicode MS;}
  tr.c39 {mso-yfti-irow:1;min-height:14.0pt}
  td.c38 {width:446.55pt;border:none;border-bottom:solid #58595B 1.0pt; mso-border-top-alt:solid white .5pt;mso-border-top-themecolor:background1; mso-border-left-alt:solid #58595B .5pt;mso-border-top-alt:solid white .5pt; mso-border-top-themecolor:background1;mso-border-left-alt:solid #58595B .5pt; mso-border-bottom-alt:solid #58595B .5pt;padding:0cm 5.4pt 0cm 5.4pt; height:14.0pt}
  p.c37 {margin-top:0cm;margin-right:1.65pt;margin-bottom: 0cm;margin-left:0cm;margin-bottom:.0001pt;text-align:justify;text-justify: inter-ideograph;line-height:normal;mso-layout-grid-align:none;text-autospace: none;vertical-align:middle}
  span.c36 {font-size:8.0pt; font-family:Arial Unicode MS;}
  td.c35 {width:86.5pt;border-top:none;border-left:solid white 1.0pt; mso-border-left-themecolor:background1;border-bottom:solid #58595B 1.0pt; border-right:solid #58595B 1.0pt;mso-border-top-alt:solid white .5pt; mso-border-top-themecolor:background1;mso-border-top-alt:white;mso-border-top-themecolor: background1;mso-border-left-alt:white;mso-border-left-themecolor:background1; mso-border-bottom-alt:#58595B;mso-border-right-alt:#58595B;mso-border-style-alt: solid;mso-border-width-alt:.5pt;padding:0cm 5.4pt 0cm 5.4pt;min-height:14.0pt}
  p.c34 {font-weight: bold; margin-right: -2.25pt; mso-add-space: auto; mso-bidi-font-weight: normal}
  span.c33 {font-size:8.0pt;line-height: 115%;font-family:Arial Unicode MS;}
  td.c32 {width:533.05pt;border:solid white 1.0pt; mso-border-themecolor:background1;border-top:none;mso-border-left-alt:solid white .5pt; mso-border-left-themecolor:background1;mso-border-bottom-alt:solid white .5pt; mso-border-bottom-themecolor:background1;mso-border-right-alt:solid white .5pt; mso-border-right-themecolor:background1;background:#CC0033;padding:0cm 5.4pt 0cm 5.4pt; height:16.3pt;mso-height-rule:exactly}
  span.c31 {font-size:8.5pt;font-family: Arial Unicode MS;color:black;mso-font-kerning:0pt;mso-fareast-language:ES}
  table.c30 {margin-left:10pt;border-collapse:collapse;mso-table-layout-alt: fixed;border:none;mso-yfti-tbllook:1184;mso-padding-alt:0cm 5.4pt 0cm 5.4pt; mso-border-insideh:none;mso-border-insidev:none}
  tr.c29 {mso-yfti-irow:2;mso-yfti-lastrow:yes;height:18.25pt;mso-height-rule: exactly}
  tr.c28 {mso-yfti-irow:1;height:18.25pt;mso-height-rule:exactly}
  td.c27 {width:92.15pt;border:none;mso-border-left-alt:solid #58595B .5pt; padding:0cm 5.4pt 0cm 5.4pt;height:18.25pt;mso-height-rule:exactly}
  td.c26 {width:49.6pt;border:none;border-right:solid #58595B 1.0pt; mso-border-left-alt:solid #58595B .5pt;mso-border-left-alt:solid #58595B .5pt; mso-border-right-alt:solid #58595B .5pt;padding:0cm 5.4pt 0cm 5.4pt; height:18.25pt;mso-height-rule:exactly}
  td.c25 {width:77.75pt;border:none;border-right:solid #58595B 1.0pt; mso-border-left-alt:solid #58595B .5pt;mso-border-left-alt:solid #58595B .5pt; mso-border-right-alt:solid #58595B .5pt;padding:0cm 5.4pt 0cm 5.4pt; height:18.25pt;mso-height-rule:exactly}
  td.c24 {width:170.35pt;border:none;border-right:solid #58595B 1.0pt; mso-border-left-alt:solid #58595B .5pt;mso-border-left-alt:solid #58595B .5pt; mso-border-right-alt:solid #58595B .5pt;padding:0cm 5.4pt 0cm 5.4pt; height:18.25pt;mso-height-rule:exactly}
  p.c23 {margin-bottom:0cm;margin-bottom:.0001pt;line-height: normal;mso-pagination:widow-orphan}
  span.c22 {font-size:8.0pt;font-family: Arial Unicode MS;}
  td.c21 {width:99.0pt;border:none;border-right:solid #58595B 1.0pt; mso-border-left-alt:solid #58595B .5pt;mso-border-left-alt:solid #58595B .5pt; mso-border-right-alt:solid #58595B .5pt;padding:0cm 5.4pt 0cm 5.4pt; height:18.25pt;mso-height-rule:exactly}
  p.c20 {margin-bottom:0cm;margin-bottom:.0001pt}
  span.c19 {font-size:8.0pt;line-height:115%;font-family:Arial Unicode MS;}
  td.c18 {width:44.2pt;border:none;border-right:solid #58595B 1.0pt; mso-border-right-alt:solid #58595B .5pt;padding:0cm 5.4pt 0cm 5.4pt; height:18.25pt;mso-height-rule:exactly}
  p.c17 {margin-top:0cm;margin-right:-2.25pt; margin-bottom:0cm;margin-left:0cm;margin-bottom:.0001pt;mso-add-space:auto; line-height:normal}
  span.c16 {font-size:8.0pt;font-family:Arial Unicode MS;}
  tr.c15 {mso-yfti-irow:0;mso-yfti-firstrow:yes;height:16.3pt;mso-height-rule: exactly}
  td.c14 {width:50pt;background:#CC0033;padding:0cm 5.4pt 0cm 5.4pt; height:16.3pt;mso-height-rule:exactly}
  td.c13 {width:50pt;background:#CC0033;padding:0cm 5.4pt 0cm 5.4pt; height:16.3pt;mso-height-rule:exactly}
  td.c12 {width:76pt;background:#CC0033;padding:0cm 5.4pt 0cm 5.4pt; height:16.3pt;mso-height-rule:exactly}
  td.c11 {width:230pt;background:#CC0033;padding:0cm 5.4pt 0cm 5.4pt; height:16.3pt;mso-height-rule:exactly}
  td.c10 {width:58pt;background:#CC0033;padding:0cm 5.4pt 0cm 5.4pt; height:16.3pt;mso-height-rule:exactly}
  td.c9 {width:40pt;background:#CC0033;padding:0cm 5.4pt 0cm 5.4pt; height:16.3pt;mso-height-rule:exactly}
  p.c8 {font-weight: bold; line-height: normal; margin-bottom: 0cm; margin-left: 0cm; margin-right: -2.25pt; margin-top: 0cm; mso-bidi-font-weight: normal}
  span.c7 {font-size:7.0pt;font-family: Arial Unicode MS;color:white;mso-themecolor:background1}
  span.c6 {font-size:8.5pt;line-height:115%; font-family:Arial Unicode MS;}
  p.c5 {margin-left:-4.0cm;text-align:justify;text-justify: inter-ideograph}
  p.c4 {margin-left:2cm;text-align:justify;text-justify: inter-ideograph}
  span.c3 {font-size:9.0pt;line-height:115%; font-family:Arial Unicode MS;}
  p.c2 {margin-top:0cm;margin-right:111.15pt;margin-bottom: 10.0pt;margin-left:2.0cm;text-align:justify;text-justify:inter-ideograph}
  span.c1 {font-size:9.0pt;line-height:115%;font-family:Arial Unicode MS; }