
       .slds {
            list-style-type: none;
        }
        .slds-form-element__label {
           
            font-size: 1rem;
            line-height: 2.5;
            margin-right: 0.75rem;
            margin-bottom: 0.25rem;
            
        }
        .Tete_de_section {
            background-color: #E2E7EE;
            margin-Top: 0px; 
            margin-bottom: 10px;
            padding-left: 10px;
            text-transform: uppercase;
        }
        span.dateFormat { display:none; } 
       .datePicker, .datePicker .dateBar ,.datePicker .calBody, .datePicker .calDays, .datePicker .buttonBar, .datePicker Select {
           display:none;
       }
       .msgIcon {
            display: none!important
        }
        .customMessage * {
            color: #fff!important
        }
        .customMessage {
            margin: 5px 0!important;
            max-width: 1280px;
            opacity: 1!important;
            width: 100%;
            font-size: 12px;
            border: 0px;
            padding-left: 10px;
        }
        .message {
            opacity: .1
        }
        
       .slds-modal__container {
          
            padding:0px;
            width:100%
        }
        .ui-state-focus {
            outline: 0;
            background-color: #f4f6f9;
            color: #16325c;
            text-decoration: none;
        }
        .slds-modal__header{
            padding: 0.3rem;
        }
        a.AESautoComplete {
            display :none;
        }    
        .slds-form-element__control{
            margin-left:2%;
            margin-right:2%; 
         }
         .etoile{      
            color: red;
            padding: 0px;
            margin-left: -9px;
            font-size: 19px;
            font-weight: 600;
        }