<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>Analysis_is_finished</fullName>
        <description>Analysis is finished</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>Footprint/FP_AnalysisDone</template>
    </alerts>
    <fieldUpdates>
        <fullName>FP_UpdateEditableField</fullName>
        <field>isEditable__c</field>
        <literalValue>0</literalValue>
        <name>FP_UpdateEditableField</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <rules>
        <fullName>FP_AnalysisIsDone</fullName>
        <actions>
            <name>Analysis_is_finished</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>FootPrint__c.isAnalysed__c</field>
            <operation>equals</operation>
            <value>True</value>
        </criteriaItems>
        <criteriaItems>
            <field>FootPrint__c.EmailMe__c</field>
            <operation>equals</operation>
            <value>True</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>FP_MakeFieldUneditable</fullName>
        <actions>
            <name>FP_UpdateEditableField</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>FootPrint__c.isEditable__c</field>
            <operation>equals</operation>
            <value>True</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
</Workflow>
